### ISSUE TITLE
KeyError: '*global*'

### ISSUE THREAD

**Issue by danbodoh** [Semi-ATE/STIL#55]
The source of this error is not so clear to me:
Syntax parsing is in progress...
Semantic analisys is in progress...
Traceback (most recent call last):
  File "/home/nxa08772/ntd/lib/lark/visitors.py", line 137, in _call_userfunc_token
    return f(token)
  File "/home/nxa08772/ntd/lib/Semi_ATE/STIL/parsers/PatternExecBlockParser.py", line 162, in b_pattern_exec__CLOSE_PATTERN_EXEC_BLOCK
    self.process_timings()
  File "/home/nxa08772/ntd/lib/Semi_ATE/STIL/parsers/PatternExecBlockParser.py", line 176, in process_timings
    self.wft2period[time_wft] = self.parse_time_expr(period)
  File "/home/nxa08772/ntd/lib/Semi_ATE/STIL/parsers/PatternExecBlockParser.py", line 261, in parse_time_expr
    sel = self.patt_exec2selector[self.curr_patt_exec]
KeyError: '*global*'

Here is the PatternExec:
PatternExec {
  Category RETARGET_cat;
  Timing RETARGET_timing;
  PatternBurst scanpats;
}

**Comment by seimit** [comment]
Dear Dan,
The error is due missing Selector statement in the PatternExec block.
This particular error in the PatternExecBlockParser is trying to parse time_expr which is not numeric value, but spec variable in the Category block. In this case, the Selector block defines which (min/typ/max) value of the spec variable must be used and this selector have to be in the pattern exec block.
I will add a code to inform the user that it is missing selector statement instead showing this exception.
Thank you for reporting this issue!
Kind Regards,
Seimit
